### PR TITLE
Navbar routing

### PR DESCRIPTION
**Pull request by 404pandas**
# JIRA Ticket:

Please include a link to the JIRA ticket that this pull request is related to:
https://mammoth-studios.atlassian.net/browse/CIS-23
https://mammoth-studios.atlassian.net/browse/CIS-25
https://mammoth-studios.atlassian.net/browse/CIS-26

## Description

This is a PR containing all my commits to add a Navbar, optimize the navbar for smaller screens, and add the requested placeholder pages, and set up the routing needed.  The following JIRA ticket requests were taken into concideration for this PR:

- Using the docs, create a browser router that is called and composes all other child routes (views) in App.tsx:
     - In App.tsx, create initial routing / views for these routes:
          - Home Screen
          - Profile / Social Screen
          - Game Screen
          - Login / Signup Screen
     - Adhere to folder structure for routes / views in Frontend Architecture doc: [Frontend Architecture](https://mammoth-studios.atlassian.net/wiki/spaces/MS/pages/1835256/Frontend+Architecture)

- Add a universal component that can be called in each top-level view / route
     - Implement a link to each of the four main pages:
          - Home
          - Login / Signup
          - Game
          - Social / Profile
     - Add the component in the /lib directory and adhere to component folder structure: [Frontend Architecture](https://mammoth-studios.atlassian.net/wiki/spaces/MS/pages/1835256/Frontend+Architecture) 
     - This component should be called / used in each top level route.
    
- After initial implementation of the Navbar component, we now need mobile - sized styling to kick in when a user reaches mobile screen sizes.
     - When we reach a certain threshold, the navbar should collapse into a burger menu
     - A drawer component should pop out and display each route name when clicking the burger menu

## Type of Change

- [ ] Bug fix
- [x] New feature
- [ ] Refactor

## Screenshot / Video

https://github.com/Mammoth-Studios/catan-in-space/assets/113853550/9a0f00b6-62ba-4777-b35c-13c202790b4b

### CODE REVIEW

**Comment by dustinjack99** [comment]
1 ticket = 1 PR

We do this to make the code reviews / changes much more readable.

Hate to do this, but that's a big process step that needs to be followed.

Bloated PRs are no bueno.

Take the time to make 3 PRs for each ticket, and the changes.

**Review by mcinerneyjake — CHANGES_REQUESTED** [review]
Just gonna block this until Dustin's feedback is complete.

Great work, Mary! 😊

**Comment by dustinjack99** [comment]
@mcinerneyjake @404pandas @ThatZiro 

Added the needed changes and reorg to the folder structure - feel free to take a look! I'm ready to rubber stamp this.

**Comment by dustinjack99** [comment]
@404pandas - You had a lot of wonderful work in this PR, and the placeholder UI looks fantastic!

Some notes:
- Keep to the 1 ticket = 1 PR process
   - Also name your git branches with this naming convention: `CIS-{TICKET_NUMBER}-feature-you-are-coding`
- Biggest critique is to not blindly copy/paste folders and files. Only make files / code when it's needed. 
- Pay attention to the frontend archeticture doc: https://mammoth-studios.atlassian.net/wiki/spaces/MS/pages/1835256/Frontend+Architecture
   - I think you had some misconceptions on the relationships between views / domains / components. So let's sync when you are able to sit back down on the project.

Overall great work, just need to work on some process / architecture knowledge 👍

**Review by dustinjack99 — DISMISSED** [review]
LGTM! (looks good to me) 😎

**Review by dustinjack99 — APPROVED** [review]

**Comment by 404pandas** [comment]
Thank you! Sorry I didn't get around to this! I'm hoping my schedule clears up soon!

**Pull request merged**
